name: Docker Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: generate image tag
      run: |
          echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
        
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/peterffyzoltan/azure-webapp-test:$IMAGE_TAG --tag ghcr.io/peterffyzoltan/azure-webapp-test:latest
        docker login ghcr.io -u peterffyzoltan -p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/peterffyzoltan/azure-webapp-test:$IMAGE_TAG
        docker push ghcr.io/peterffyzoltan/azure-webapp-test:latest

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'valami'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_14416cb817fe4c07a434b0391b098215 }}
        images: 'ghcr.io/peterffyzoltan/azure-webapp-test:${{ env.IMAGE_TAG }} '
